Repository immoonancient/YTSubtitles, pull requests merged in 2019-08, with the labels that each got.

#9 翻译稿 20190801-三轮车熏肉
  subtitles/xue-yu/20190801-三轮车熏肉
Labels: 雪鱼探店

#17 Create 20190804-修土灶
  subtitles/wang-gang/20190804-xiu-tu-zao
Labels: 美食作家王刚

#52 20190812 保定驴肉火烧
  subtitles/xue-yu/20190812-bao-ding-lv-rou-huo-shao
Labels: 雪鱼探店

#55 create-20190805-lu-rou-huo-shao
  subtitles/xue-yu/190805-lu-rou-huo-shao
Labels: 雪鱼探店

#62 Create 20190816-Yan-Ju-Hai-Xian
  subtitles/wang-gang/20190816-Yan-Ju-Hai-Xian
Labels: 待审阅

#84 190819-wang-gang-chu-li-zhu-shu
  subtitles/wang-gang/190819-huanongs-bamboo-rat
Labels: unlist, 待上传, 待审阅

#90 Create 20190822-pan-long-qie-zi
  subtitles/wang-gang/20190822-pan-long-qie-zi
Labels: 待审阅, 美食作家王刚

#89 Create 20190814-niu-rou-zhao-bing
  subtitles/xue-yu/20190814-niu-rou-zhao-bing
Labels: 待审阅, 雪鱼探店

#111 Create 190828-mang-gan-qi
  190828-mang-gan-qi
Labels: 华农兄弟

#116 20190829 油炸蜂蛹
  subtitles/wang-gang/20190829-zha-feng-yong.sbv
Labels: unlisted, 待审阅, 美食作家王刚
