Repository immoonancient/YTSubtitles, pull requests merged in 2019-09, with the labels that each got.

#125 20190831 華農兄弟釣魚
  subtitles/hua-nong-brothers/20190831-huanong-catch-fish.sbv
Labels: 华农兄弟, 待审阅

#124 20190831 華農兄弟借公鼠
  subtitles/hua-nong-brothers/20190831-borrow-male-rats.sbv
Labels: 华农兄弟, 待审阅

#121 20190831 華農兄弟擼狗
  subtitles/hua-nong-brothers/20190831-play-dogs.svg
Labels: 华农兄弟, 待审阅

#117 Create 2019-09-02-kao-zhu-shu.txt
  subtitles/wang-gang/2019-09-02-kao-zhu-shu.txt
Labels: unlisted, 待审阅, 美食作家王刚

#132 華農兄弟 2019 兔子
  subtitles/hua-nong-brothers/20190901-huanong-bunnies.sbv
Labels: 华农兄弟, 待审阅

#133 華農兄弟 第二次借公鼠
  subtitles/hua-nong-brothers/20190901-huanong-borrow-male-rats-2.sbv
Labels: 华农兄弟, 待审阅

#152 190904-yan-shao-jiang-mu-ya
  subtitles/xue-yu/190904-yan-shao-jiang-mu-ya
Labels: 雪鱼探店

#151 Create 20190907-kai-wei-qing-jiao.sbv
  subtitles/wang-gang/20190907-kai-wei-qing-jiao.sbv
Labels: 待审阅, 美食作家王刚

#154 Create fu-jian-niu-pai
  subtitles/xue-yu/20190905-fu-jian-niu-pai
Labels: 雪鱼探店

#157 满煎糕
  subtitles/xue-yu/20190906-man-jian-gao.sbv
Labels: 雪鱼探店

#164 帶王剛抓魚
  subtitles/hua-nong-brothers/20190907-Wanggang_catch-fish.sbv
Labels: 华农兄弟, 待审阅

#169 糖醋排骨
  subtitles/wang-gang/20190908-tang-cu-pai-gu.sbv
Labels: 美食作家王刚

#171 #170 带王刚摘板栗
  subtitles/hua-nong-brothers/20190908-Wanggang-chestnuts.sbv
Labels: 华农兄弟, 待审阅

#177 190910-Fu-Jian-Yu-Yuan
  subtitles/xue-yu/190909-Fu-Jian-Yu-Yuan
Labels: 待审阅, 雪鱼探店

#179 #175 木槿花
  subtitles/hua-nong-brothers/20190910-chicken-flower.sbv
Labels: 华农兄弟, 待审阅

#182 坐飞机
  subtitles/wang-gang/20190910-zuo-fei-ji.sbv
Labels: 美食作家王刚

#189 Fo tiao qiang
  subtitles/xue-yu/20190909-fo-tiao-qiang.sbv
Labels: 待审阅, 雪鱼探店

#190 带四伯看竹鼠
  subtitles/wang-gang/20190914-kan-zhu-shu.sbv
Labels: 美食作家王刚

#191 壶仔饭
  subtitles/xue-yu/20190912-hu-zai-fan.sbv
Labels: 雪鱼探店

#194 Create 190915-Hua-nong-jia-zhai-ye-guo
  subtitles/wang-gang/190915-Hua-nong-jia-zhai-ye-guo.sbv
Labels: 美食作家王刚

#192 #188 [华农兄弟] 新毙鼠山庄
  subtitles/hua-nong-brothers/20190914-new-concentration-camp.sbv
Labels: 华农兄弟, 待审阅

#195 #185 【美食作家王刚】去华农家摸鱼烤竹鼠
  subtitles/wang-gang/20190915-catch-bbq.txt
Labels: unlisted, 美食作家王刚

#206 锅边糊
  subtitles/xue-yu/20190918-guo-bian-hu.sbv
Labels: 待审阅, 雪鱼探店

#204 190917-artificial meat
  subtitles/wang-gang/20190918-ren-zao-rou.sbv
Labels: 美食作家王刚

#202 烧牛腩
  subtitles/wang-gang/20190918-shao-niu-nan.sbv
Labels: 待审阅, 美食作家王刚

#161 190907- Qing jiao chao dan
  subtitles/wang-gang/190902-qing-jiao-chao-ji-dan.sbv
Labels: 美食作家王刚, 老视频补字幕

#212 新疆烤包子
  subtitles/xue-yu/20190922-kao-bao-zi.sbv
Labels: 雪鱼探店

#205 手工麻糍
  subtitles/xue-yu/20190915-shou-gong-ma-ci.sbv
Labels: 待审阅, 雪鱼探店

#217 190924-hong-shao-shi-zi-tou
  subtitles/wang-gang/190924-hong-shao-shi-zi-tou.sbv
Labels: 美食作家王刚

#221 新疆烤馕
  subtitles/xue-yu/20190924-xin-jiang-kao-nang.srt
Labels: 雪鱼探店

#223 川味牛肉面
  subtitles/wang-gang/20190930-niu-rou-mian.sbv
Labels: 美食作家王刚

#228 羊肉手抓饭
  subtitles/xue-yu/20190927-shou-zhua-fan.sbv
Labels: 雪鱼探店

#230 [华农兄弟] 摘野生猕猴桃
  subtitles/hua-nong-brothers/20190928-huanong-kiwifruit.sbv
Labels: 华农兄弟, 待审阅

#232 [华农兄弟] 外出归来检查竹鼠 - https://youtu.be/bPILO_IUQww
  subtitles/hua-nong-brothers/20190929-huanong-check-rats.sbv
Labels: 华农兄弟, 待审阅

#233 [华农兄弟] 放地笼抓螃蟹
  subtitles/hua-nong-brothers/20190929-huanong-crabs.sbv
Labels: 华农兄弟, 待审阅

#234 [华农兄弟] 摘摄影小哥家的板栗和南瓜
  subtitles/hua-nong-brothers/20190929-huanong-chestnutspumpkins.sbv
Labels: 华农兄弟, 待审阅

#235 20190930 ganbianfeichang
  subtitles/wang-gang/20190930-gan-bian-fei-chang.sbv
Labels: 美食作家王刚
