Repository immoonancient/YTSubtitles, pull requests merged in 2019-11, with the labels that each got.

#357 买野猪
  subtitles/wang-gang/20191101-mai-ye-zhu.sbv
Labels: 美食作家王刚

#359 姜葱焗鲤鱼
  subtitles/wang-gang/191102-jiang-cong-ju-li-yu.sbv
Labels: 美食作家王刚

#363 焊烤架
  subtitles/wang-gang/20191103-han-kao-jia.sbv
Labels: 美食作家王刚

#365 Create 20191104-kao-ye-zhu.sbv
  subtitles/wang-gang/20191104-kao-ye-zhu.sbv
Labels: 美食作家王刚

#366 [华农兄弟] 华农兄弟摘点老王家的柿子尝一下顺便再去摘点野果
  subtitles/hua-nong-brothers/20191104-fruits.sbv
Labels: 华农兄弟

#368 Create 191107_Qing-dao-zhi-zha.srt
  subtitles/xue-yu/191107_Qing-dao-zhi-zha.srt
Labels: 雪鱼探店

#369 Add files via upload
  subtitles/xue-yu/191106-qing-dao-fan-dian.sbv
Labels: 雪鱼探店

#378 木须肉
  subtitles/wang-gang/20191109-mu-xu-rou.sbv
Labels: 美食作家王刚

#379 Create 191108 kai-guo
  subtitles/wang-gang/191108-kai-guo
Labels: 美食作家王刚

#375 [华农兄弟] 华农兄弟捡点拐枣泡酒路过兄弟的玉米地搞点来喂猪
  subtitles/hua-nong-brothers/20191108-oriental-raisins.sbv
Labels: 华农兄弟

#374 [华农兄弟] 华农兄弟把兄弟家的竹鼠通通搬到我们新场房去还有花竹鼠哦
  subtitles/hua-nong-brothers/20191108-relocate-rats.sbv
Labels: 华农兄弟

#383 [华农兄弟] 华农兄弟看一下我们家的脐橙熟了没有顺便摘一点回去吃
  subtitles/hua-nong-brothers/20191110-naveloranges.sbv
Labels: 华农兄弟

#384 Leng-chi-niu-rou
  subtitles/wang-gang/191111-leng-chi-niu-rou.sbv
Labels: 美食作家王刚

#388 191112-la-zhu-shu
  subtitles/wang-gang/191112-La-Zhu-Shu.sbv
Labels: 美食作家王刚

#389 Create 191113-Kaoji_Bazirou.srt
  subtitles/xue-yu/191113-Kaoji_Bazirou.sbv
Labels: 雪鱼探店

#386 Create doujiangyoutiao
  subtitles/xue-yu/20191112-dou-jiang-you-tiao.sbv
Labels: 雪鱼探店

#397 [华农兄弟] 华农兄弟小狗又胖了狗妈妈又怀孕了这下真的一地都是狗了
  subtitles/hua-nong-brothers/20191115-manydogs.sbv
Labels: 华农兄弟

#396 [华农兄弟] 华农兄弟兄弟家的油柿子熟了一树都是带老弟去摘点
  subtitles/hua-nong-brothers/20191115-persimmons.sbv
Labels: 华农兄弟

#393 Create 20191114-si-bo-fen-jie-zhu-rou.sbv
  subtitles/wang-gang/20191114-si-bo-fen-jie-zhu-rou.sbv
Labels: 美食作家王刚

#406 [华农兄弟] 华农兄弟受邀参加第十七届中国国际农产品交易会带大家看一下 - https://youtu.be/4XIsCa6D24I
  subtitles/hua-nong-brothers/20191119-agricultural-trade-fair.sbv
Labels: 华农兄弟

#402 [华农兄弟] 华农兄弟砍点场里的红象草喂竹鼠看它们抢来抢去的很喜欢吃
  subtitles/hua-nong-brothers/20191119-red-elephant-grass.sbv
Labels: 华农兄弟

#405 [华农兄弟] 华农兄弟瓜瓜瘦了差点认不出来了小胖却越来越胖了
  subtitles/hua-nong-brothers/20191119-Guagua-Fatties.sbv
Labels: 华农兄弟

#410 Create 20191120-Yingtaorou.sbv
  subtitles/wang-gang/20191120-Yingtaorou.sbv
Labels: 美食作家王刚

#416 [华农兄弟] 华农兄弟参加赣南脐橙比赛拿了个第一顺便去天龙山玩了一下
  subtitles/hua-nong-brothers/20191121-oranges-tianlungshan.txt
Labels: 华农兄弟

#418 [华农兄弟] 华农兄弟把全部猪放出来散养摸一下大公猪它竟然想咬我
  subtitles/hua-nong-brothers/20191122-pigs.sbv
Labels: 华农兄弟

#425 [华农兄弟] 华农兄弟一年又快过去了兄弟家野池塘的鱼也长大了网点来煎
  subtitles/hua-nong-brothers/20191126-fish-dogs-pigs.sbv
Labels: 华农兄弟

#423 【美食作家王刚】琥珀桃仁挂霜核桃 - https://youtu.be/BppHmtbwT30
  subtitles/wang-gang/20191127-ambered-walnut-candy.sbv
Labels: 美食作家王刚

#429 [华农兄弟] 华农兄弟狗子又下崽了带大家看一下顺便给香猪喂点酒糟
  subtitles/hua-nong-brothers/20191127-puppes-pigs.sbv
Labels: 华农兄弟

#431 全家吃火锅
  subtitles/wang-gang/20191128-chi-huo-guo.sbv
Labels: 美食作家王刚

#434 [华农兄弟] 华农兄弟把小猪放出来了它又可以跟狗子们一起吃喝玩乐了
  subtitles/hua-nong-brothers/20191128-pigs.sbv
Labels: 华农兄弟

#432 [华农兄弟] 华农兄弟喂点粉丝送的狗粮给狗子吃看它们抢来抢去好像很好吃
  subtitles/hua-nong-brothers/20191128-feed-dogs.sbv
Labels: 华农兄弟

#438 [华农兄弟] 华农兄弟猪吃酒糟醉了叫兄弟帮忙一起宰猪烤起来很香哦
  subtitles/hua-nong-brothers/20191129-kill-pigs.sbv
Labels: 华农兄弟
