Repository immoonancient/YTSubtitles, pull requests merged in 2019-10, with the labels that each got.

#229 [华农兄弟] 抓6只竹鼠去王刚跟山药家玩
  subtitles/hua-nong-brothers/20190928-six-bamboo-rats.sbv
Labels: 华农兄弟, 待审阅

#244 191002-tu-fei-zhu-gan
  subtitles/wang-gang/191002-tu-fei-zhu-gan.sbv
Labels: 美食作家王刚

#246 烤全羊
  subtitles/xue-yu/20191002-kao-quan-yang.sbv
Labels: 雪鱼探店

#250 【美食作家王刚】王刚华农烤竹鼠
  subtitles/wang-gang/20191004-gill-bamboo-rats.sbv
Labels: 美食作家王刚

#249 [华农兄弟] 华农兄弟这只小香猪胖得跟猪一样其它都瘦了
  subtitles/hua-nong-brothers/20191004-feed-pigs.sbv
Labels: 华农兄弟, 待审阅

#247 Create 191003-LeShan_Giant_Buddha
  subtitles/wang-gang/191003-LeShan_Giant_Buddha.sbv
Labels: unlisted, 待审阅, 美食作家王刚

#256 [华农兄弟] 华农兄弟去新场地做一些竹鼠池顺便去旁边的小河看一下
  subtitles/hua-nong-brothers/20191006-buildling-new-concentration-camp.sbv
Labels: 华农兄弟

#257 191007-kao-rou-kao-bao-zi.sbv
  subtitles/xue-yu/191007-kao-rou-kao-bao-zi.sbv
Labels: 雪鱼探店

#258 20191007-za-cai-chao-dan
  subtitles/wang-gang/20191007-za-cai-chao-dan.sbv
Labels: 美食作家王刚

#265 [华农兄弟] 华农兄弟挖点摄影小哥家的番薯刚好他女儿也来了叫她帮忙捡番薯
  subtitles/20191007-potatoes.sbv
Labels: 华农兄弟

#260 [华农兄弟] 华农兄弟搞点邻居大婶家的黄豆来吃放点盐煮 一煮很嫩很好吃
  subtitles/hua-nong-brothers/20191007-neighbour-beans.sbv
Labels: 华农兄弟

#270 #[华农兄弟] 华农兄弟秋天了给母鼠放点稻草其它公鼠等冬天再放
  subtitles/hua-nong-brothers/20191008-straw.sbv
Labels: 华农兄弟

#269 [华农兄弟] 华农兄弟老婆最近心情不好摘点草珠子做一串项链给她
  subtitles/hua-nong-brothers/20191008-bead-necklace.sbv
Labels: 华农兄弟

#268 191008- Nong bo hui
  subtitles/wang-gang/191008-nong-bo-hui.sbv
Labels: 美食作家王刚

#286 Create 20191012_Mai_Yang
  subtitles/wang-gang/20191012_Mai_Yang.sbv
Labels: 美食作家王刚

#281 Create 20191012-Niu-Wa-Yu-Tou
  subtitles/wang-gang/20191012-Niu-Wa-Yu-Tou.sbv
Labels: 美食作家王刚

#282 将Google Drive对译表添加到translation.md
  docs/template.md
  docs/translation-table.md
  docs/translation.md
  subtitles/wang-gang/README.md
Labels: documentation

#288 [华农兄弟] 华农兄弟突然想吃去烫皮河边搞点沙子来炒很香哦
  subtitles/hua-nong-brothers/20191013-tangpi.sbv
Labels: 华农兄弟

#291 Create 20191014_Fu_zhou_da_wan_fen
  subtitles/xue-yu/20191014_Fu_zhou_da_wan_fen.sbv
Labels: 雪鱼探店

#292 [华农兄弟] 华农兄弟带老弟上山砍竹子顺便看一下山上的野果熟了没有
  subtitles/hua-nong-brothers/20191014-wildfruits.sbv
Labels: 华农兄弟

#296 191016-congshaoliyu
  subtitles/wang-gang/191014-congshaoliyu.sbv
Labels: 待上传, 待审阅, 美食作家王刚

#297 蜂窝玉米
  subtitles/wang-gang/20191017-feng-wo-yu-mi.sbv
Labels: 美食作家王刚

#301 [华农兄弟] 华农兄弟河里面好多鱼我们去钓一下顺便网一点来吃
  subtitles/hua-nong-brothers/20191016-catchfish.sbv
Labels: 华农兄弟

#299 Create kao-dan
  subtitles/xue-yu/20191010-kao-dan.sbv
Labels: 雪鱼探店

#302 Create 20191015-guilin-mi-fen
  subtitles/xue-yu/20191015-guilin-mi-fen.sbv
Labels: 待审阅, 雪鱼探店

#304 [华农兄弟] 华农兄弟摘两个西红柿来吃顺便摘点给小猪吃再抓它称一下
  subtitles/hua-nong-brothers/20191017-weighpig.sbv
Labels: 华农兄弟

#307 [华农兄弟] 华农兄弟看一下写名字的拿藤果熟了没有顺便摘点南瓜跟玉米
  subtitles/hua-nong-brothers/20191018-pumpkinchestnut.sbv
Labels: 华农兄弟

#313 [华农兄弟] 华农兄弟给猪打扫一下猪窝再给一些稻草跟南瓜给它们
  subtitles/hua-nong-brothers/20191019-feedpigs.sbv
Labels: 华农兄弟

#312 Create 191019_Nuo_mi_fan.sbv
  subtitles/xue-yu/191019_Nuo_mi_fan.srt
Labels: 雪鱼探店

#319 [华农兄弟] 华农兄弟竹鼠日常喂养喂点米糠拌饭看它们吃得多开心
  subtitles/hua-nong-brothers/20191020-feed-bamboorats.sbv
Labels: 华农兄弟

#318 [华农兄弟] 华农兄弟铁门烂掉了我们用铁丝绑一下避免狗子到处乱跑
  subtitles/hua-nong-brothers/20191020-fix-gates.sbv
Labels: 华农兄弟

#314 Create 20191021-kao-yang-rou
  subtitles/wang-gang/20191021-kao-yang-rou
Labels: 待审阅, 美食作家王刚

#278 猪脚饭
  subtitles/dao-yue-she/20191007-zhu-jiao-fan.sbv
Labels: 盗月社食遇记

#322 191022-fried-meatballs
  subtitles/wang-gang/191022-fried-meatballs.sbv
Labels: 美食作家王刚

#324 [华农兄弟] 华农兄弟帮房东把山上的小竹子砍掉拿去喂我们家的竹鼠
  subtitles/hua-nong-brothers/20191022-chopbamboo.sbv
Labels: 华农兄弟

#325 Create zhu-fa
  subtitles/xue-yu/zhu-fa
Labels: 雪鱼探店

#328 [华农兄弟] 华农兄弟发现在路边好多青菜摘点来吃顺便再摘点黄豆和萝卜
  subtitles/hua-nong-brothers/20191025-vegatables.sbv
Labels: 华农兄弟

#331 Create 191023-tu-dou-zha-xiang-jiao
  subtitles/wang-gang/191023-tu-dou-zha-xiang-jiao
Labels: 待审阅, 美食作家王刚

#330 [华农兄弟] 华农兄弟竹鼠和老鼠放一起会怎么样上山抓只老鼠回来试一下
  subtitles/hua-nong-brothers/20191025-mice.sbv
Labels: 华农兄弟

#333 柳州螺蛳粉
  subtitles/xue-yu/20191026-luo-si-fen.sbv
Labels: 雪鱼探店

#336 [华农兄弟] 华农兄弟山上的一些野果熟了叫上兄弟们一去边摘边吃
  subtitles/hua-nong-brothers/20191027-wildfruits.sbv
Labels: 华农兄弟

#337 竹筒饭
  subtitles/xue-yu/20191022-zhu-tong-fan.sbv
Labels: 雪鱼探店

#339 191027-Cola-Chicken-Wings
  subtitles/wang-gang/191027-cola-chicken-wings.sbv
Labels: 美食作家王刚

#344 [华农兄弟] 华农兄弟去兄弟家的池塘钓鱼钓了一会钓不到幸好带了抽水机
  subtitles/hua-nong-brothers/20191028-catchfish.sbv
Labels: 华农兄弟

#345 如何挑选酱油
  subtitles/wang-gang/20191030-tiao-xuan-jiang-you.sbv
Labels: 美食作家王刚

#347 [华农兄弟] 华农兄弟参观5000亩的赣南脐橙产业园再找兄弟要点脐橙送粉丝
  subtitles/hua-nong-brothers/20191029-navaloranges.sbv
Labels: 华农兄弟

#349 [华农兄弟] 华农兄弟老弟带回来7只小狗这下真的是一地都是狗了
  subtitles/hua-nong-brothers/20191029-puppies.sbv
Labels: 华农兄弟

#354 [华农兄弟] 华农兄弟把新场地的黄蜂窝搞掉不然到时候住人会被蜇
  subtitles/hua-nong-brothers/20191030-wasp-nest.sbv
Labels: 华农兄弟

#356 [华农兄弟] 华农兄弟平时在家随便搞点菜吃今天兄弟来了多煎两个蛋
  subtitles/hua-nong-brothers/20191031-meal.sbv
Labels: 华农兄弟
