Repository immoonancient/YTSubtitles, pull requests merged in 2019-12, with the labels that each got.

#445 [华农兄弟] 华农兄弟搞了一点葛根虫子用油一炸嘎嘣脆很好吃哦
  subtitles/hua-nong-brothers/20191201-kudzu-root-worms.sbv
Labels: 华农兄弟

#442 [华农兄弟] 华农兄弟场里的橘子快熟了摘一个尝一下顺便看一下小猪崽
  subtitles/hua-nong-brothers/20191130-piglets.sbv
Labels: 华农兄弟

#440 [华农兄弟] 华农兄弟天气越来越冷了给小狗子做一个温暖的窝
  subtitles/hua-nong-brothers/20191130-puppies.sbv
Labels: 华农兄弟

#444 191201-huang-men-ji
  subtitles/wang-gang/191202-huang-men-ji.sbv
Labels: 美食作家王刚

#451 猪肉涨价问答
  subtitles/wang-gang/20191204-zhu-rou-zhang-jia.sbv
Labels: 美食作家王刚

#446 Create wu-xiang-rou-tiao
  subtitles/xue-yu/20191124-wu-xiang-rou-tiao.sbv
Labels: 雪鱼探店

#456 [华农兄弟] 华农兄弟抓了只鸡刚好兄弟来了一起烤鸡顺便再烤点排骨
  subtitles/hua-nong-brothers/20191206-grill-with-wanggang.sbv
Labels: 华农兄弟

#458 【美食作家王刚】烤鸡烤猪排 - https://youtu.be/aUBTGWlyxFM
  subtitles/hua-nong-brothers/20191207-grill-with-huanong.txt
Labels: 美食作家王刚

#461 【美食作家王刚】参观兄弟家的猪和竹鼠 - https://youtu.be/z0M01HwpnM4
  subtitles/wang-gang/20191207-visit-huanong.txt
Labels: 美食作家王刚

#460 [华农兄弟] 华农兄弟最近天气干燥摄影小哥又上火了挖点葛根来炖竹鼠
  subtitles/hua-nong-brothers/20191207-kuduz-root-soup.sbv
Labels: 华农兄弟

#468 [华农兄弟] 华农兄弟才十几天小狗子和小猪崽就长肥了不少胖墩墩的
  subtitles/hua-nong-brothers/20191209-puppies-piglets.sbv
Labels: 华农兄弟

#471 Create 191209_Xiao_jian_hua_lian
  subtitles/wang-gang/191209_Xiao_jian_hua_lian
Labels: 美食作家王刚

#473 [华农兄弟] 华农兄弟抬了个兄弟家的烤炉回来顺便再去抓只兄弟家的鸡来烤
  subtitles/hua-nong-brothers/20191210-roast-chicken.sbv
Labels: 华农兄弟

#467 Update translation-table.md
  docs/translation-table.md
Labels: documentation

#474 Create 191211_kai_guo_jian_dan.sbv
  subtitles/wang-gang/191211_kai_guo_jian_dan.sbv
Labels: 美食作家王刚

#481 [华农兄弟] 华农兄弟先把兄弟送的红鲤鱼放池子里养着再去摘点他家的柿子来吃
  subtitles/hua-nong-brothers/20191213-fish-permissons.sbv
Labels: 华农兄弟

#477 Create Fu-jian-wu-xing -xiao-dian
  subtitles/xue-yu/20191211-fu-jian-wu-xing-xiao-dian.srt
Labels: 雪鱼探店

#485 [华农兄弟] 华农兄弟又到了吃虫子的季节放点孜然烤一烤又香又脆很美味哦
  subtitles/hua-nong-brothers/20191214-worms.sbv
Labels: 华农兄弟

#493 [华农兄弟] 华农兄弟小狗子已经睁眼会爬了把它们捉出来晒晒太阳
  subtitles/hua-nong-brothers/20191215-puppies.sbv
Labels: 华农兄弟

#491 [华农兄弟] 华农兄弟兄弟家地里长了很多野生的百香果摘两个来尝一下
  subtitles/hua-nong-brothers/20191215-passion-fruits.sbv
Labels: 华农兄弟

#489 Create 191215-again-kai-guo-jian-dan
  subtitles/wang-gang/191215-again-kai-guo-jian-dan
Labels: 美食作家王刚

#498 [华农兄弟] 华农兄弟摘点大叔家的香菇捉2只兄弟家的小鸡做美味的小鸡炖蘑菇
  subtitles/hua-nong-brothers/20191216-chickens-mushrooms.sbv
Labels: 华农兄弟

#495 Create pork-intestine-blood.srt
  subtitles/xue-yu/20191215-pork-intestine-blood.srt
Labels: 雪鱼探店

#500 [华农兄弟] 华农兄弟老妈养的鸡下了不少蛋其中几个像小鸟蛋一样大
  subtitles/hua-nong-brothers/20191217-eggs.sbv
Labels: 华农兄弟

#502 Create 191218-techniques for processing pork tripe
  subtitles/wang-gang/191218-techniques-for-processing-por-tripe.sbv
Labels: 待审阅, 美食作家王刚

#507 [华农兄弟] 华农兄弟喂点网友送的猪饲料给小猪吃顺便捉只猪崽玩一下
  subtitles/hua-nong-brothers/20191220-feed-pigs.sbv
Labels: 华农兄弟

#510 [华农兄弟] 华农兄弟称一下养了几个小月的小狗子看起来小称起来还挺重的
  subtitles/hua-nong-brothers/20191220-weigh-dogs.sbv
Labels: 华农兄弟

#513 [华农兄弟] 华农兄弟天冷看一下竹鼠有没有感冒顺便丢点稻草给猪做窝
  subtitles/hua-nong-brothers/20191221-check-bamboo-rats.sbv
Labels: 华农兄弟

#514 Create yan-la-rou.sbv
  subtitles/wang-gang/20191222-yan-la-rou.sbv
Labels: 美食作家王刚

#515 自贡鲜锅兔
  subtitles/wang-gang/191223-xian-guo-tu.sbv
Labels: 美食作家王刚

#519 [华农兄弟] 华农兄弟上山砍竹子顺便挖点竹笋回去炒腊肉很好吃哦
  subtitles/hua-nong-brothers/20191224-bamboo-shoots.sbv
Labels: 华农兄弟

#505 描述字幕组岗位
  docs/team-roles.md
Labels: documentation

#524 [华农兄弟] 华农兄弟看一下被霜打死的象草再去拔几个老弟种得萝卜来吃
  subtitles/hua-nong-brothers/2191225-elephant-grass-radish.sbv
Labels: 华农兄弟

#527 [华农兄弟] 华农兄弟摘几朵茶花尝一下再去摘点竹节果尝一下
  subtitles/hua-nong-brothers/20191226-tea-mangosteen.sbv
Labels: 华农兄弟

#518 Create gui-yang-nuo-mi-fan
  subtitles/xue-yu/20191221-gui-yang-nuo-mi-fan.srt
Labels: 雪鱼探店

#531 [华农兄弟] 华农兄弟有只竹鼠托梦给我想吃竹笋去挖个来炖它
  subtitles/hua-nong-brothers/20191228-bamoo-shoots-bamboo-rats.sbv
Labels: 华农兄弟

#532 Create 20191228-fu-shun-dou-hua.sbv
  subtitles/wang-gang/20191228-fu-shun-dou-hua.sbv
Labels: 美食作家王刚
