Repository immoonancient/YTSubtitles, pull requests merged in 2020-02, with the labels that each got.

#635 Create 200205-cai-ban-ri-chang-bao-yang.sbv
  subtitles/wang-gang/200205-cai-ban-ri-chang-bao-yang.sbv
Labels: 美食作家王刚

#636 添加老饭骨视频描述中固定部分的翻译
  subtitles/lao-fan-gu/README.md
Labels: 老饭骨

#647 Create ting_geng_shuo_ming.sbv
  subtitles/wang-gang/ting_geng_shuo_ming.sbv
Labels: 美食作家王刚

#643 200210-da-lu-mian
  subtitles/lao-fan-gu/200210-da-lu-mian.srt
Labels: 老饭骨

#624 发财鸭
  subtitles/lao-fan-gu/20200129-Fa-Cai-Ya.sbv
Labels: 老饭骨

#667 蒜蓉辣椒酱
  subtitles/wang-gang/20200214-jia-chang-suan-rong-la-jiao-jiang.sbv
Labels: 美食作家王刚

#673 儿菜棒菜字幕完成
  subtitles/wang-gang/200217-er-cai-bang-cai
Labels: 美食作家王刚

#682 Create Lao_shi_gong_bao_ji_ding.sbv
  subtitles/lao-fan-gu/Lao_shi_gong_bao_ji_ding.srt
Labels: 老饭骨

#683 鲜椒千层肚
  subtitles/wang-gang/200217-qian-jiao-qian-ceng-du.sbv
Labels: 美食作家王刚

#691 Create 200218_Zhe_er_gen_chao_la_rou.sbv
  subtitles/wang-gang/200218_Zhe_er_gen_chao_la_rou.sbv
Labels: 美食作家王刚

#690 Create 200218_Er_cai_wu_hua_rou.sbv
  subtitles/wang-gang/200218_Er_cai_wu_hua_rou.sbv
Labels: 美食作家王刚

#702 Create 20200220 fu-jian-xian-dou-hua
  subtitles/xue-yu/20200220 fu-jian-xian-dou-hua.srt
Labels: 雪鱼探店

#722 Create 20200225_Kan_You_Cai_Hua.sbv
  subtitles/wang-gang/20200225_Kan_You_Cai_Hua.sbv
Labels: 美食作家王刚
