Repository immoonancient/YTSubtitles, pull requests merged in 2020-01, with the labels that each got.

#539 [华农兄弟] 华农兄弟天气不错把小狗抱到楼下来玩肥肥的很可爱
  subtitles/20191231-puppies.sbv
Labels: 华农兄弟

#537 Create 191231-Jia Sha Rou
  subtitles/wang-gang/20191231-jia-sha-rou.sbv
Labels: 美食作家王刚

#541 Create 20200101-bao-zai-fan.srt
  subtitles/xue-yu/20200101-bao-zai-fan.srt
Labels: 雪鱼探店

#546 [华农兄弟] 华农兄弟关着的猪一下没注意跑出来好几条看到什么都吃
  subtitles/hua-nong-brothers/20200102-pigs.sbv
Labels: 华农兄弟

#551 Create 200103-tian_su_rou
  subtitles/wang-gang/20200103-tian_su_rou.sbv
Labels: 待审阅, 美食作家王刚

#552 [华农兄弟] 华农兄弟搞点米糠拌饭把小猪骗回去再把猪栏修一下
  subtitles/hua-nong-brothers/20200103-pigs.sbv
Labels: 华农兄弟

#558 [华农兄弟] 华农兄弟带大家看一下花竹鼠顺便看一下它的崽很漂亮哦
  subtitles/hua-nong-brothers/20200104-tinted-bamboo-rats.sbv
Labels: 华农兄弟

#549 Create 191229-gui-yang-chang-wang-mian.srt
  subtitles/xue-yu/191229-gui-yang-chang-wang-mian.srt
Labels: 雪鱼探店

#564 [华农兄弟] 华农兄弟猪又跑出来了没办法只好喂点好吃的给它们
  subtitles/hua-nong-brothers/20200106-feed-pigs.sbv
Labels: 华农兄弟

#567 Upload la shao jia yu
  subtitles/wang-gang/200106-la-shao-jia-yu.sbv
Labels: 美食作家王刚

#565 【雪鱼】烧鹅-https://youtu.be/NIY6aPsSe3s
  subtitles/xue-yu/20200104-roast-geese.srt
Labels: 雪鱼探店

#574 200110-xian-shao-bai.sbv
  subtitles/wang-gang/200110-xian-shao-bai.sbv
Labels: 美食作家王刚

#575 Add files via upload
  subtitles/wang-gang/200112-Kou-Zhou-Zi.sbv
Labels: 美食作家王刚

#582 dou-fu-zhu-ni-qiu subtitle finished
  subtitles/wang-gang/200115-dou-fu-zhu-ni-qiu.sbv
Labels: 美食作家王刚

#591 Add files via upload
  subtitles/wang-gang/20200118-shui-zhu-ji-pian.sbv
Labels: 美食作家王刚

#594 Create 20200118-sheng-gun-zhou
  subtitles/xue-yu/20200118-sheng-gun-zhou.sbv
Labels: 雪鱼探店

#595 kao-yu finished
  subtitles/wang-gang/200120-kao-yu.sbv
Labels: 美食作家王刚

#603 200122-xie-dui-lian
  subtitles/wang-gang/200122-xie-dui-lian.sbv
Labels: 美食作家王刚

#605 Update 200122-xie-dui-lian.sbv
  subtitles/wang-gang/200122-xie-dui-lian.sbv
Labels: 美食作家王刚

#596 Create 200114-Zheng-zhu
  subtitles/xue-yu/200114-Zheng-zhu.srt
Labels: 雪鱼探店

#615 【美食作家王刚】坝坝宴 - https://youtu.be/3V9fkm4wZN0
  subtitles/wang-gang/20200125-ba-ba-banquet.sbv
Labels: 美食作家王刚
